### ISSUE TITLE
Level 1 and Level 2 consistency?

### ISSUE THREAD

**Issue by tetomonti** [montilab/OmicSignature#3]
Just checking: are the feature symbols in level 1 and level 2/3 checked for consistency?
I.e., if one uses gene_symbols in `difexp=...` and probeset IDs in `signature=...`, will the inconsistency be caught?

Also, notice that when creating an OmicSignature independently of SigRepoR, the symbols can be arbitrary (whichever the user chooses, as long as they are consistent). However, when creating an OmicSignature to be uploaded to SigRepo, there should be checks for whether one of the accepted 'vocabularies'  is adopted (i.e., either gene symbols, or uniprot ids, or HMDB ids, etc.)
Will include this issue in SigRepoR as well.

**Comment by Vanessa104** [comment]
Yes. When creating a new OmcSignature, the id and symbol in the signature will be checked against the id and symbol in the difexp. An error will occur if any of them are missing, so one cannot use different set of ids or symbols. 
And yes, at the OmicSignature level, there is no restriction about what the users use for ids and symbols, as long as the ids are not duplicated.
