### ISSUE TITLE
Flat signatures

### ISSUE THREAD

**Issue by anfederico** [montilab/OmicSignature#7]
I'm trying to upload disease gene signatures. These are not from differential expression analyses but rather from curated sets of previously identified disease-associated genes. Each gene has a "Disease-Association Score". 

It's not from a sequencing platform, so I don't have a GEO-approved platform. I get an error here because this field is required. 

Ideally it would look like this:
```
metadata <- list(
    "signature_name" = "Alzheimers Disease",
    "organism" = "Homo sapiens",
    "platform" = NA,
    "phenotype" = NA,
    "direction_type" = "uni-directional",
    "disease_id" = "C0002395",
    "download_date" = "June 9, 2020",
    "keywords" = c("disease")
)
```

Another issue is I get an error on the signature which I cannot seem to debug:

```
OmicObj <- OmicSignature$new(
    metadata = metadata,
    signature = signature,
    difexp = NULL
)
```

The signature is a named numeric vector that looks like this:
```
A2M   ACHE ADAM10   AMFR   BIN1  APOC1 
0.50   0.40   0.70   0.31   0.50   0.50 
```

I get:
```
Signature not found in OmicSignature object or signature is not a dataframe. Or, if you are trying to modify the signature, the new signature you are inputting is not valid.
```

Perhaps it is being too strict in that it seems to always expect a signature coming from differential expression analyses from sequencing data?

**Comment by tanya-karagiannis** [comment]
I agree with Anthony that some of the parameters such as the GEO platform might be better set as optional. I currently do not have the GEO platform information for example for my own signatures generated from multiple datasets and I think other users may not have this information as well.

**Comment by Vanessa104** [comment]
Thanks for the feedback! 

- Now phenotype and platform are not required. Set phenotype as NULL or "unknown", and platform as NULL or "GPLXXXXX" if they are not available. 
- For the "named numeric signature vector": `signature` is saved as a data frame with columns "signature_symbol", "signature_score" (optional) and "signature_direction" (optional) in the object. But I also updated the code so now it can take a numeric or character vector as the signature. It will run [signatureVecToDF()](https://montilab.github.io/OmicSignature/reference/signatureVecToDF.html) if you provide a vector as signature when creating the `OmicSignature` object. 

~Vanessa

**Comment by Vanessa104** [comment]
quick example:

```
meta <- createMetadata(signature_name = "Hello", direction_type = "uni", organism = "homo sapiens")
sig <- c(0.2, 0.4, 0.3)
names(sig) <- c("g1", "g2", "g3")
oms <- OmicSignature$new(metadata = meta, signature = sig)
```
