### ISSUE TITLE
Structure of OmicSignature ...

### ISSUE THREAD

**Issue by tetomonti** [montilab/OmicSignature#8]
**OmicSignature**
The little diagram lists "logfc","aveexpr","fdr" for the difexp object. Are these the _required_ fields? If not, replace w/ the required fields.

**OmicSignatureCollection**
When creating an OmicSignatureCollection, does the list require names? If not, how do I refer to one of the signatures in the collection?
Also, when I call `OmicCol$extract.signature(...)`, what does it return? A new collection? Something else?
Lastly, aren't the function names supposed to follow the lowCamelCase naming convention?
See https://docs.google.com/document/d/1NMNow00K7UJYBI4EKSneQbkduYo90QBaLWJgyM60zqQ

**Read/Write**
Doesn't this also support rds-based read/write?

**Comment by Vanessa104** [comment]
vignette updated.
